### ISSUE TITLE
Mysql ketarin Job not updating package 

### ISSUE THREAD

**Issue by zagarachi** [ferventcoder/chocolateyautomaticpackages#76]
Just pulled down the repo to test what ketarin was detecting as the current mysql version, it seems that it is finding the correct version 5.6.17 but it is either not running or failing to complete in the nightly updates, so the current version remains at 5.6.15, which is no longer available for download.

**Comment by ferventcoder** [comment]
I think this has been fixed. Closing as this has been moved out of this repo - if you believe this is still something to implement, let's discuss it over at https://github.com/ferventcoder/chocolatey-packages/issues
